<?php

return ['groups' => [
    'images' => ['label' => 'Website images', 'fields' => [
        'site_logo_image' => '/images/brand/amcham-logo.png',
        'about_hero_image' => '/images/amcham-live/boards.jpg',
        'our_work_hero_image' => '/images/amcham-live/boards.jpg',
        'board_hero_image' => '/images/amcham-live/boards.jpg',
        'membership_hero_image' => '/images/amcham-live/hero-minara.jpg',
        'membership_application_hero_image' => '/images/amcham-live/hero-minara.jpg',
        'events_hero_image' => '/images/amcham-live/thanksgiving.png',
        'events_fallback_image' => '/images/amcham-live/thanksgiving.png',
        'news_hero_image' => '/images/amcham-live/tic-news.jpg',
        'news_fallback_image' => '/images/amcham-live/tic-news.jpg',
        'members_hero_image' => '/images/amcham-live/hero-minara.jpg',
        'resources_hero_image' => '/images/amcham-live/boards.jpg',
        'newsletters_hero_image' => '/images/amcham-live/tic-news.jpg',
        'policy_updates_hero_image' => '/images/amcham-live/tic-news.jpg',
        'gallery_hero_image' => '/images/amcham-live/thanksgiving.png',
        'contact_hero_image' => '/images/amcham-live/hero-minara.jpg',
        'login_hero_image' => '/images/amcham-live/hero-minara.jpg',
        'register_hero_image' => '/images/amcham-live/hero-minara.jpg',
        'trade_hero_image' => '/images/amcham-live/tic-news.jpg',
        'investment_hero_image' => '/images/amcham-live/boards.jpg',
    ]],
    'header' => ['label' => 'Header & navigation', 'fields' => [
        'brand_name' => 'AmCham Tanzania', 'brand_descriptor' => 'American Chamber of Commerce',
        'nav_home' => 'Home', 'nav_about' => 'About', 'nav_our_work' => 'Our Work', 'nav_data' => 'Data', 'nav_membership' => 'Membership', 'nav_events' => 'Events',
        'nav_news' => 'Newsroom', 'nav_members' => 'Members', 'nav_resources' => 'Resources', 'nav_gallery' => 'Gallery',
        'nav_contact' => 'Contact', 'nav_login' => 'Member Login', 'nav_join' => 'Join AMCHAM',
    ]],
    'authentication' => ['label' => 'Login & registration screens', 'fields' => [
        'auth_brand_name' => 'AmCham Tanzania',
        'auth_brand_descriptor' => 'American Chamber of Commerce',
        'auth_panel_eyebrow' => 'AMCHAM Tanzania platform',
        'auth_panel_heading' => 'Secure access for members, administrators and chamber staff.',
        'auth_panel_description' => 'Manage membership, events, publications, campaigns, approvals and company profiles from one professional platform.',
        'auth_public_site_link' => 'Public site',
        'auth_return_link' => 'Return to public website',
        'login_eyebrow' => 'Secure login',
        'login_heading' => 'Access AMCHAM Tanzania',
        'login_description' => 'Sign in to manage the chamber platform, member workspace, content approvals and campaigns.',
        'login_access_prompt' => 'Need access for your company?',
        'login_register_link' => 'Register a member account',
        'register_eyebrow' => 'Member access',
        'register_heading' => 'Create your AMCHAM account',
        'register_description' => 'Start your member workspace for company profile management, event participation, publication submissions and AMCHAM communications.',
        'register_review_notice' => 'AMCHAM staff will review your application, contact you, and approve your access to the member portal.',
    ]],
    'footer' => ['label' => 'Footer', 'fields' => [
        'footer_stay_informed' => 'Stay informed', 'footer_email_placeholder' => 'Your email address',
        'footer_subscribe_success' => 'Subscribed — thank you.', 'footer_quick_links' => 'Quick Links',
        'footer_useful_links' => 'Useful Links', 'footer_contact' => 'Get in touch',
        'footer_copyright' => 'American Chamber of Commerce in Tanzania. All rights reserved.',
        'footer_privacy' => 'Privacy Policy', 'footer_terms' => 'Terms & Conditions',
        'footer_cookies' => 'Cookie Policy', 'footer_cookie_settings' => 'Cookie settings',
    ]],
    'board' => ['label' => 'Board members page', 'fields' => [
        'board_hero_eyebrow' => 'Leadership', 'board_hero_title' => 'The leaders guiding the chamber.',
        'board_hero_description' => 'Meet the business leaders volunteering their experience, judgement and networks to advance AMCHAM Tanzania.',
        'board_section_eyebrow' => 'Governance', 'board_section_title' => 'A board drawn from the business community.',
        'board_section_description' => 'Our directors represent the breadth of the U.S.–Tanzania commercial relationship and serve the chamber on behalf of its members.',
        'board_empty' => 'Board member profiles will be published soon.',
    ]],
    'trade_investment' => ['label' => 'Trade & Investment Data pages', 'fields' => [
        'trade_hero_eyebrow' => 'Trade Data', 'trade_hero_title' => 'U.S.–Tanzania trade at a glance.',
        'trade_hero_description' => 'Bilateral trade-in-goods and services figures between the United States and Tanzania, compiled from official government and multilateral sources.',
        'investment_hero_eyebrow' => 'Investment Data', 'investment_hero_title' => 'U.S.–Tanzania investment at a glance.',
        'investment_hero_description' => 'Foreign direct investment flows and stock between the United States and Tanzania, compiled from official government and multilateral sources.',
    ]],
    'events' => ['label' => 'Events pages', 'fields' => [
        'events_hero_title' => 'Where the business community meets.',
        'events_hero_description' => 'Policy briefings, executive roundtables, flagship celebrations and practical conversations that move business forward.',
        'events_spotlight_eyebrow' => 'Coming up', 'events_spotlight_title' => 'Featured event.',
        'events_spotlight_description' => 'Reserve your place at the chamber’s next convening.',
        'events_browse_eyebrow' => 'Event calendar', 'events_browse_title' => 'Find your next conversation.',
        'events_search_placeholder' => 'Search events…', 'events_empty' => 'No events match your search yet.',
        'event_register_title' => 'Register for this event', 'event_register_button' => 'Submit registration',
    ]],
    'news' => ['label' => 'News pages', 'fields' => [
        'news_hero_title' => 'News and insight from the chamber.',
        'news_hero_description' => 'Policy updates, member news and investment guides from AMCHAM Tanzania and its member companies.',
        'news_spotlight_eyebrow' => 'Editorial spotlight', 'news_spotlight_title' => 'Featured publication.',
        'news_spotlight_description' => 'The chamber’s latest perspective on the issues shaping business, investment and bilateral opportunity.',
        'news_search_placeholder' => 'Search publications…', 'news_empty' => 'No publications match your search yet.',
    ]],
    'members' => ['label' => 'Member directory', 'fields' => [
        'members_hero_title' => 'The companies shaping U.S.–Tanzania business.',
        'members_hero_description' => 'American and Tanzanian companies across banking, healthcare, energy, mining and logistics call AMCHAM Tanzania home.',
        'members_section_eyebrow' => 'Explore the network', 'members_section_title' => 'Meet our members.',
        'members_section_description' => 'Discover the organizations investing, innovating and building stronger commercial ties between Tanzania and the United States.',
        'members_search_placeholder' => 'Search companies, sectors or services…', 'members_empty_title' => 'No matching members',
        'members_empty_body' => 'Try a different company name or explore all sectors.', 'members_clear' => 'Clear all filters',
        'members_cta_eyebrow' => 'Your company belongs here', 'members_cta_title' => 'Join the network shaping bilateral business.',
        'members_cta_body' => 'Build trusted connections, strengthen your voice and access opportunities across Tanzania and the United States.',
        'members_cta_button' => 'Explore membership',
    ]],
    'resources' => ['label' => 'Resources & newsletters', 'fields' => [
        'resources_hero_title' => 'A resource library for investors, members and partners.',
        'resources_hero_description' => 'Investor guides, policy briefs and membership materials to help your business navigate the Tanzanian market.',
        'newsletters_hero_title' => 'Updates and insight from the chamber.',
        'newsletters_hero_description' => 'Read and download AMCHAM Tanzania newsletters featuring chamber news, member updates, events and business insight.',
        'resources_knowledge_title' => 'Knowledge you can use',
        'resources_knowledge_body' => 'Curated insight for members, investors and partners operating across both markets.',
        'resources_browse_eyebrow' => 'Browse the library', 'resources_browse_title' => 'Insight for informed decisions.',
        'resources_browse_body' => 'Download practical material prepared by the chamber and its trusted partners.',
        'resources_search_placeholder' => 'Search resources…', 'newsletters_search_placeholder' => 'Search newsletters…',
        'resources_cta_eyebrow' => 'Stay ahead', 'resources_cta_title' => 'Get chamber insight in your inbox.',
        'resources_cta_button' => 'Connect with the Secretariat',
    ]],
    'gallery' => ['label' => 'Gallery', 'fields' => [
        'gallery_hero_title' => 'Moments from the AMCHAM community.',
        'gallery_hero_description' => 'Events, delegations and conversations connecting business leaders across Tanzania and the United States.',
        'gallery_section_eyebrow' => 'Photo library', 'gallery_section_title' => 'The chamber in action.',
        'gallery_empty' => 'Gallery images will be published soon.',
    ]],
    'membership' => ['label' => 'Membership page & application', 'fields' => [
        'membership_choose_eyebrow' => 'Choose your membership', 'membership_choose_title' => 'Clear benefits. The right level of access.',
        'membership_choose_body' => 'Review every benefit and price before starting your application. Your selected tier remains with you while you create or access your account.',
        'membership_included' => 'Everything included', 'membership_best_for' => 'Best for:',
        'application_eyebrow' => 'Membership application', 'application_description' => 'Review the exact membership details below, then complete your organisation information.',
        'application_selected' => 'Your selected tier', 'application_form_title' => 'Applicant and organisation details',
    ]],
    'contact' => ['label' => 'Contact page & forms', 'fields' => [
        'contact_form_title' => 'Send us a message', 'contact_form_button' => 'Send message',
        'contact_details_title' => 'Contact details', 'contact_hours_title' => 'Office hours',
    ]],
    'legal' => ['label' => 'Legal pages', 'fields' => [
        'privacy_title' => 'Privacy Policy', 'privacy_body' => 'AMCHAM Tanzania respects your privacy and handles personal information responsibly. Information submitted through membership, event, contact and subscription forms is used only to provide chamber services and communications.',
        'terms_title' => 'Terms and Conditions', 'terms_body' => 'By using this website, you agree to use its content and services lawfully. Event, membership and resource information may be updated by AMCHAM Tanzania at any time.',
        'cookies_title' => 'Cookie Policy', 'cookies_body' => 'This website uses essential cookies for security, authentication and core functionality. Optional analytics cookies are used only with your permission.',
    ]],
]];
